Repository christina-cook/rancid-tomatillos, pull requests merged in 2021-02, with the labels that each got.

#8 Feature/create components
  .eslintcache
  src/App.js
  src/App/App.css
  src/App/App.js
  src/App/App.test.js
  src/Card/Card.css
  src/Card/Card.js
  src/Data/movieData.js
  src/Movies/Movies.css
  src/Movies/Movies.js
  src/index.js
Labels: Component

#9 Feature style components
  .eslintcache
  public/index.html
  src/App/App.css
  src/App/App.js
  src/Card/Card.css
  src/Card/Card.js
  src/Movies/Movies.css
  src/Movies/Movies.js
  src/assets/star.png
  src/assets/tomatillo.png
Labels: CSS

#16 Feature display movie details
  .eslintcache
  src/App/App.js
  src/Card/Card.js
  src/MovieDetails/MovieDetails.css
  src/MovieDetails/MovieDetails.js
  src/Movies/Movies.js
Labels: Component

#18 Feature/style movie display
  .eslintcache
  public/index.html
  src/App/App.css
  src/App/App.js
  src/MovieDetails/MovieDetails.css
  src/MovieDetails/MovieDetails.js
Labels: CSS

#20 Feature/api requests
  .eslintcache
  src/App/App.js
  src/Data/API.js
  src/Data/movieData.js
  src/MovieDetails/MovieDetails.js
  src/Movies/Movies.js
Labels: Component

#21 Feature add header component
  .eslintcache
  src/App/App.css
  src/App/App.js
  src/Card/Card.css
  src/Card/Card.js
  src/Header/Header.css
  src/Header/Header.js
  src/MovieDetails/MovieDetails.css
  src/MovieDetails/MovieDetails.js
  src/MovieDetailsHeader/MovieDetailsHeader.css
  src/MovieDetailsHeader/MovieDetailsHeader.js
  src/Movies/Movies.js
  src/SideBar/SideBar.css
  src/SideBar/SideBar.js
  src/assets/home.png
Labels: CSS

#35 Feature api conditionals
  .eslintcache
  package.json
  src/Card/Card.js
  src/Header/Header.js
  src/MovieDetails/MovieDetails.js
  src/MovieDetailsHeader/MovieDetailsHeader.js
  src/Movies/Movies.js
  src/SideBar/SideBar.js
Labels: enhancement

#38 Feature/router
  .eslintcache
  package-lock.json
  package.json
  src/App/App.js
  src/Card/Card.js
  src/Header/Header.js
  src/MovieDetails/MovieDetails.js
  src/MovieDetailsHeader/MovieDetailsHeader.js
  src/SideBar/SideBar.css
  src/SideBar/SideBar.js
  src/index.js
Labels: Component, enhancement

#39 Feature refactor cypress tests
  .eslintcache
  cypress/fixtures/example.json
  cypress/fixtures/testMovieData.json
  cypress/integration/rancid_tomatillos_spec.js
  src/App/App.js
  src/Card/Card.js
  src/Header/Header.js
  src/MovieDetails/MovieDetails.js
  src/MovieDetailsHeader/MovieDetailsHeader.js
  src/Movies/Movies.js
Labels: testing

#41 Feature/display trailers
  .eslintcache
  package-lock.json
  package.json
  src/App/App.js
  src/Data/API.js
  src/MovieDetails/MovieDetails.css
  src/MovieDetails/MovieDetails.js
Labels: enhancement

#44 Refactor css to sass
  .eslintcache
  cypress/integration/rancid_tomatillos_spec.js
  package-lock.json
  package.json
  src/App/App.css
  src/App/App.js
  src/App/App.scss
  src/Card/Card.js
  src/Card/Card.scss
  src/Header/Header.css
  src/Header/Header.js
  src/Header/Header.scss
  src/MovieDetails/MovieDetails.js
  src/MovieDetails/MovieDetails.scss
  src/MovieDetailsHeader/MovieDetailsHeader.css
  src/MovieDetailsHeader/MovieDetailsHeader.js
  src/MovieDetailsHeader/MovieDetailsHeader.scss
  src/Movies/Movies.js
  src/Movies/Movies.scss
  src/SideBar/SideBar.js
  src/SideBar/SideBar.scss
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
  src/styles/_mixins.scss
  src/styles/_variables.scss
  src/styles/base.scss
Labels: CSS

#53 Feature add ratings
  .eslintcache
  src/App/App.js
  src/Card/Card.js
  src/Card/Card.scss
  src/Form/Form.js
  src/Header/Header.js
  src/Header/Header.scss
  src/MovieDetails/MovieDetails.js
  src/Movies/Movies.js
  src/SideBar/SideBar.js
  src/SideBar/SideBar.scss
  src/Sort/Sort.js
  src/Sort/Sort.scss
  src/assets/sort.png
Labels: Component

#61 Feature/testing search sort
  .eslintcache
  cypress/integration/rancid_tomatillos_spec.js
  src/Form/Form.js
Labels: testing

#62 Feature responsive design
  .eslintcache
  public/index.html
  src/App/App.scss
  src/Card/Card.scss
  src/Form/Form.scss
  src/Header/Header.js
  src/Header/Header.scss
  src/MovieDetails/MovieDetails.scss
  src/MovieDetailsHeader/MovieDetailsHeader.js
  src/MovieDetailsHeader/MovieDetailsHeader.scss
  src/Movies/Movies.js
  src/Movies/Movies.scss
  src/Sort/Sort.scss
Labels: CSS

#64 Refactor css
  .eslintcache
  src/App/App.scss
  src/Card/Card.js
  src/Card/Card.scss
  src/Form/Form.js
  src/Form/Form.scss
  src/Header/Header.js
  src/Header/Header.scss
  src/MovieDetails/MovieDetails.scss
  src/MovieDetailsHeader/MovieDetailsHeader.scss
  src/Movies/Movies.js
  src/Movies/Movies.scss
  src/SideBar/SideBar.scss
  src/Sort/Sort.js
  src/Sort/Sort.scss
  src/styles/_mixins.scss
  src/styles/_variables.scss
Labels: CSS
